name: Deploy to NCP

on:
  push:
    branches:
      - main  # main 브랜치에 push 시 실행
  pull_request:
    branches:
      - main  # main 브랜치에 PR 머지 시 실행
name: Deploy app

on:
  push:
    branches:
      - main  # 메인 브랜치에 푸시될 때 동작

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 리포지토리 클론
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. 필요한 패키지 설치 (sshpass 등)
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    # 3. 프록시 서버를 경유하여 본 서버로 SSH 접속 및 app.py 파일 전송
    - name: Deploy app via SSH
      env:
        PROXY_IP: ${{ secrets.PROXY_IP }}           # 프록시 서버 IP
        PROXY_USER: ${{ secrets.PROXY_USER }}       # 프록시 서버 유저명
        TARGET_IP: ${{ secrets.TARGET_IP }}         # 본 서버 IP
        TARGET_USER: ${{ secrets.TARGET_USER }}     # 본 서버 유저명
        TARGET_PASSWORD: ${{ secrets.TARGET_PASSWORD }}  # 본 서버 비밀번호
      run: |
        # 4. 프록시 서버를 경유하여 본 서버에 SSH 접속 및 비밀번호 자동 입력
        sshpass -p "$TARGET_PASSWORD" ssh -o StrictHostKeyChecking=no \
          -o ProxyCommand="ssh -W %h:%p -o StrictHostKeyChecking=no $PROXY_USER@$PROXY_IP" \
          $TARGET_USER@$TARGET_IP << 'EOF'
          
          # 5. 리포지토리에서 app.py 파일을 본 서버로 복사
          cd /path/to/app/folder   # 서버의 배포 경로로 이동
          git pull origin main     # 최신 코드 가져오기
          
          # 6. 앱 실행
          nohup python3 app.py &   # app.py 파일 실행 (백그라운드에서)
          
          exit
          EOF
