name: Deploy to NCP

on:
  push:
    branches:
      - main  # 메인 브랜치에 푸시될 때 동작

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Expect
      run: sudo apt-get install -y expect

    - name: Upload app.py via Proxy
      env:
        PROXY_USER: ${{ secrets.PROXY_USER }}
        PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}
        PROXY_HOST: ${{ secrets.PROXY_HOST }}
        TARGET_USER: ${{ secrets.TARGET_USER }}
        TARGET_PASSWORD: ${{ secrets.TARGET_PASSWORD }}
        TARGET_HOST: ${{ secrets.TARGET_HOST }}
      run: |
        # Expect script to SSH into the proxy server and then to the target server
        expect << EOF
        set timeout -1

        # Connect to Proxy Server
        spawn ssh -o StrictHostKeyChecking=no ${env(PROXY_USER)}@${env(PROXY_HOST)}
        expect "password:"
        send "${env(PROXY_PASSWORD)}\r"

        # Connect to Target Server via Proxy
        expect "$ "
        send "ssh -o StrictHostKeyChecking=no ${env(TARGET_USER)}@${env(TARGET_HOST)}\r"
        expect "password:"
        send "${env(TARGET_PASSWORD)}\r"

        # Upload the file (assuming your repo is checked out in the current directory)
        expect "$ "
        send "scp app.py ${env(TARGET_USER)}@${env(TARGET_HOST)}:~/app.py\r"
        expect "password:"
        send "${env(TARGET_PASSWORD)}\r"

        # Exit from target server and proxy server
        expect "$ "
        send "exit\r"
        expect "$ "
        send "exit\r"

        expect eof
        EOF
