name: Deploy to NCP

on:
  push:
    branches:
      - main  # 메인 브랜치에 푸시될 때 동작

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Expect Script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROXY_HOST }}
        username: ${{ secrets.PROXY_USER }}
        password: ${{ secrets.PROXY_PASSWORD }}
        port: ${{ secrets.PROXY_PORT }}
        TARGET_HOST: ${{ secrets.TARGET_HOST }}
        TARGET_USER: ${{ secrets.TARGET_USER }}
        TARGET_PASSWORD: ${{ secrets.TARGET_PASSWORD }}
        script: |
          whoami
          cd /root/tnote
          ls
          send "ssh -o StrictHostKeyChecking=no $env(TARGET_USER)@$env(TARGET_HOST)\r"
          expect "password:"
          send "$env(TARGET_PASSWORD)\r"