name: Deploy to NCP

on:
  push:
    branches:
      - main  # main 브랜치에 push 시 실행
  pull_request:
    branches:
      - main  # main 브랜치에 PR 머지 시 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Copy files via SSH
      env:
        NCP_HOST: ${{ secrets.NCP_HOST }}
        NCP_USER: ${{ secrets.NCP_USER }}
      run: |
        echo "${{ secrets.NCP_KEY }}" > key.pem
        chmod 400 key.pem
        scp -o StrictHostKeyChecking=no -i key.pem -r * $NCP_USER@$NCP_HOST:/home/$NCP_USER/app/

    - name: Restart server on NCP
      env:
        NCP_HOST: ${{ secrets.NCP_HOST }}
        NCP_USER: ${{ secrets.NCP_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem $NCP_USER@$NCP_HOST 'sudo systemctl restart my-python-app.service'
