name: Deploy to NCP

on:
  push:
    branches:
      - main  # 메인 브랜치에 푸시될 때 동작


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Add ACG rule in NCP
      run: |
        curl -X POST "https://ncloud.apigw.ntruss.com/vpc/v2/addAccessControlGroupRule" \
        -H "Content-Type: application/json" \
        -H "X-NCP-APIGW-API-KEY-ID: ${{ secrets.NCP_API_KEY_ID }}" \
        -H "X-NCP-APIGW-API-KEY: ${{ secrets.NCP_API_KEY }}" \
        -d '{
          "regionNo": "1",
          "accessControlGroupNo": "${{ secrets.ACG_NO }}",
          "protocolTypeCode": "TCP",
          "portRange": "22",
          "accessControlGroupRuleDescription": "Allow SSH access from GitHub Actions",
          "sourceIp": "${{ steps.get_ip.outputs.ip }}/32"
        }'
