name: Deploy to NCP

on:
  push:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Expect Script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROXY_HOST }}
        username: ${{ secrets.PROXY_USER }}
        password: ${{ secrets.PROXY_PASSWORD }}
        port: ${{ secrets.PROXY_PORT }}
        script: |
          sh /root/tnote/tnoteSSH.sh